# Course Scheduling Optimization System - Configuration File
# This file contains all configurable parameters for algorithms, experiments, and system behavior.
#
# Usage: Modify values here instead of changing code
# Format: YAML (be careful with indentation!)

# =============================================================================
# SYSTEM SETTINGS
# =============================================================================
system:
  # Project directories (relative to project root)
  data_dir: "data"
  instances_dir: "data/instances"
  results_dir: "data/results"
  logs_dir: "logs"

  # Default execution limits
  max_execution_time: 900  # seconds (5 minutes)
  memory_limit_mb: 2048    # MB

  # Logging configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    console_output: true
    file_output: true
    log_convergence: true

  # Parallel execution
  parallel:
    enabled: false  # Set to true for multi-processing
    max_workers: 4  # Number of parallel workers
    chunk_size: 1   # Experiments per chunk

# =============================================================================
# EXPERIMENT SETTINGS
# =============================================================================
experiments:
  # Default settings for batch experiments
  defaults:
    runs_per_combination: 3
    save_results: true
    save_convergence: true
    timeout_per_run: 900
    verbose: false

  # Statistical analysis settings
  statistics:
    confidence_level: 0.95
    significance_threshold: 0.05
    effect_size_thresholds:
      small: 0.2
      medium: 0.5
      large: 0.8

  # Result file management
  files:
    auto_cleanup: false
    max_result_files: 1000
    compress_old_results: true
    backup_interval_days: 7

# =============================================================================
# BENCHMARK PROFILES
# =============================================================================
benchmark_profiles:
  # Quick test - single instance, basic algorithms
  quick:
    description: "Fast test for development and debugging"
    instances: "small/small_01"
    algorithms: ["greedy"]
    runs_per_combination: 1
    max_time_per_run: 60

  # Development testing - multiple small instances
  dev:
    description: "Development testing with small instances"
    instances: "small/*"
    algorithms: ["greedy", "genetic"]
    runs_per_combination: 2
    max_time_per_run: 60

  # Algorithm comparison - main algorithms
  comparison:
    description: "Compare main algorithms on small instances"
    instances: "small/*"
    algorithms: ["greedy", "genetic", "sa", "tabu", "vns"]
    runs_per_combination: 3
    max_time_per_run: 900

  # Variant testing - test all algorithm variants
  variants:
    description: "Test algorithm variants and parameter sensitivity"
    instances: "large/*"
    algorithms: ["greedy_variants", "genetic_variants", "sa_variants"]
    runs_per_combination: 3
    max_time_per_run: 900

  # Scaling test - different instance sizes
  scaling:
    description: "Test algorithm scalability across instance sizes"
    instances: "*/*"
    algorithms: ["greedy", "genetic", "sa"]
    runs_per_combination: 5
    max_time_per_run: 300

  # Full benchmark - comprehensive testing
  full:
    description: "Complete benchmark with all algorithms and instances"
    instances: "*/*"
    algorithms: "all"
    runs_per_combination: 5
    max_time_per_run: 900
    require_confirmation: true

# =============================================================================
# ALGORITHM SETTINGS
# =============================================================================
algorithms:
  # NOTE: Algorithm variants are defined in their respective Python files
  # (e.g., create_greedy_variants() in greedy.py)
  # This section only contains system-level algorithm settings

  # Global algorithm settings
  global:
    default_timeout: 900  # seconds
    default_random_seed: null
    save_convergence_history: true
    validate_solutions: true

  # Default execution parameters (can be overridden per algorithm)
  execution_defaults:
    verbose: false
    save_results: true
    max_iterations: 1000
    early_stopping: true

  # Algorithm-specific timeout overrides
  timeouts:
    greedy: 60        # Greedy should be fast
    genetic: 600      # GA can take longer
    simulated_annealing: 900
    tabu_search: 900
    vns: 600

  # Memory and performance settings
  performance:
    cache_solutions: true
    parallel_evaluation: false
    memory_limit_mb: 1024

# =============================================================================
# ANALYSIS SETTINGS
# =============================================================================
analysis:
  # Statistical analysis configuration
  statistical_tests:
    default_test: "wilcoxon"  # wilcoxon, t_test, mann_whitney
    multiple_comparison_correction: "bonferroni"  # bonferroni, holm, fdr
    min_samples_for_test: 3

  # Performance metrics
  metrics:
    primary_objective: "objective_value"
    secondary_metrics: ["execution_time", "feasibility_rate", "utilization"]
    normalization: "none"  # none, z_score, min_max

  # Ranking and comparison
  ranking:
    criteria: ["avg_objective", "success_rate", "robustness_score"]
    weights: [0.5, 0.3, 0.2]  # Must sum to 1.0
    tie_breaker: "avg_time"

  # Report generation
  reports:
    include_statistical_tests: true
    include_convergence_plots: true
    include_parameter_sensitivity: true
    export_formats: ["markdown", "csv"]
    decimal_precision: 3

# =============================================================================
# VISUALIZATION SETTINGS
# =============================================================================
visualization:
  # Plot styling
  style:
    theme: "seaborn-v0_8"  # matplotlib style
    figure_size: [12, 8]
    dpi: 300
    font_size: 12
    color_palette: "Set2"

  # Plot types to generate
  plots:
    convergence_curves: true
    performance_comparison: true
    statistical_significance: true
    parameter_sensitivity: true
    instance_difficulty: true
    algorithm_profiling: true

  # Export settings
  export:
    formats: ["png", "pdf"]
    save_individual: true
    create_combined_report: true
    interactive_plots: false  # Set to true for plotly

  # Animation settings (for convergence)
  animation:
    enabled: false
    fps: 2
    duration_seconds: 10

# =============================================================================
# INSTANCE GENERATION (for future use)
# =============================================================================
instance_generation:
  # Parameters for generating synthetic instances
  small:
    courses: [3, 5, 8]
    rooms: [2, 3, 4]
    instructors: [2, 3, 4]
    time_horizon: [15, 20, 25]

  medium:
    courses: [10, 15, 20]
    rooms: [5, 8, 10]
    instructors: [5, 8, 10]
    time_horizon: [30, 40, 50]

  large:
    courses: [30, 50, 100]
    rooms: [10, 15, 20]
    instructors: [10, 15, 20]
    time_horizon: [60, 80, 100]

  # Constraint density settings
  constraints:
    instructor_course_compatibility: [0.3, 0.5, 0.8]  # Low, medium, high
    room_course_compatibility: [0.4, 0.6, 0.9]
    instructor_availability: [0.4, 0.6, 0.8]

# =============================================================================
# ADVANCED SETTINGS
# =============================================================================
advanced:
  # Memory management
  memory:
    clear_cache_frequency: 100  # Clear every N experiments
    max_solution_cache: 1000
    compress_large_results: true

  # Debugging and development
  debug:
    save_intermediate_solutions: false
    track_memory_usage: false
    profile_performance: false
    validate_all_solutions: true

  # Experimental features
  experimental:
    hybrid_algorithms: false
    online_parameter_tuning: false
    distributed_computing: false
    real_time_visualization: false

# =============================================================================
# USER PREFERENCES
# =============================================================================
user_preferences:
  # Interface settings
  interface:
    show_progress_bars: true
    colored_output: true
    sound_notifications: false
    auto_open_results: false

  # Default behaviors
  defaults:
    always_save_results: true
    confirm_long_experiments: true
    auto_analyze_after_benchmark: false
    preferred_analysis_focus: "overview"

  # Notification settings
  notifications:
    email_on_completion: false
    email_address: ""
    slack_webhook: ""
    desktop_notifications: true
